### ISSUE TITLE
automatically detect single vs multiple confounds

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/fmriprep_load_confounds#18]
Instead of introducing a new method load_confounds_multi, it would be more elegant to test if the tsv file provided by the user is a string (in which case a single confound array is loaded) or an array (in which case the method would iterate on all inputs).

**Comment by HanadS** [comment]
I renamed `load_confounds` to` _load_confounds_helper` and `load_confounds_multi` to `load_confounds`. Then I do the check there
