### ISSUE TITLE
only expose well known strategies

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/fmriprep_load_confounds#22]
Of the strategies currently listed, only "minimal" is a true preprocessing strategy. 
The others are "private" strategies, used internally to assemble more complex strategies. 
They should not be listed in the documentation of the main public method.

**Comment by HanadS** [comment]
@pbellec I deleted some documentation because I felt it was repetitive. Let me know if you disagree

**Comment by pbellec** [comment]
I don't think this issue should be closed. There are still many strategies documented in `load_confounds` which are not meant to be used.
