### ISSUE TITLE
support multiple confounds

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/fmriprep_load_confounds#8]
some procedures (eg nilearn's group dictionary learning) require to pass a list of datasets. It would be useful to support such a list, and return a list of confound arrays.

**Comment by HanadS** [comment]
By a list of datasets do you mean a list of 'raw' CSV files? Or is this issue intertwined with issue #9?

**Comment by pbellec** [comment]
The point here would be to iterate on an array of inputs, if presented with
one.

If we separately implement #9, then it would support array of niftis.
But starting with arrays of tsv files would be great.
