### ISSUE TITLE
support nifti file names

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/fmriprep_load_confounds#9]
when working with nilearn, it will often be the case that users have built a list of nifti file names they want to load. It would be useful to let them pass such list directly to the confound loader. As fmriprep uses a systematic naming schemes, we could automatically search for the corresponding confound files. We may also support niftiimage object, which carry the file name in their attributes. https://nilearn.github.io/manipulating_images/input_output.html

This way users would simply need to pass their list of `imgs` to get back the `confounds` arrays, ready to be fed in a `NiftiMasker` or any nilearn function with a `confound` argument.

**Comment by HanadS** [comment]
I agree this would be useful

**Comment by HanadS** [comment]
I made the changes. Users need to input the bold preprocessed data and the confounds file has to be in the same directory.

**Comment by pbellec** [comment]
this is great, thanks @HanadS !
